links:

  - name: "link-001"
    friendly_name: "doc-sdnsw1:1 → pom-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 1
      port_name: "doc-sdnsw1 Port 1"
    destination:
      switch: "10.127.0.138"
      port: "unknown"
      port_name: "pom-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-002"
    friendly_name: "doc-sdnsw1:2 → csm-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 2
      port_name: "doc-sdnsw1 Port 2"
    destination:
      switch: "10.127.0.179"
      port: "unknown"
      port_name: "csm-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-003"
    friendly_name: "doc-sdnsw1:3 → nhl-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 3
      port_name: "doc-sdnsw1 Port 3"
    destination:
      switch: "10.127.0.123"
      port: "unknown"
      port_name: "nhl-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-004"
    friendly_name: "doc-sdnsw1:4 → emf-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 4
      port_name: "doc-sdnsw1 Port 4"
    destination:
      switch: "10.127.0.203"
      port: "unknown"
      port_name: "emf-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-005"
    friendly_name: "doc-sdnsw1:5 → msf-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 5
      port_name: "doc-sdnsw1 Port 5"
    destination:
      switch: "10.127.0.221"
      port: "unknown"
      port_name: "msf-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-006"
    friendly_name: "doc-sdnsw1:7 → vss-router1.scrravss.net                         |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 7
      port_name: "doc-sdnsw1 Port 7"
    destination:
      switch: "10.120.0.1"
      port: "unknown"
      port_name: "vss-router1.scrravss.net                         | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-007"
    friendly_name: "doc-sdnsw1:18 → vss-aggsw01                                      |:Unknown"
    source:
      switch: "10.127.0.200"
      port: 18
      port_name: "doc-sdnsw1 Port 18"
    destination:
      switch: "10.120.0.29"
      port: "unknown"
      port_name: "vss-aggsw01                                      | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-008"
    friendly_name: "pom-sdnsw1:21 → moc-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.138"
      port: 21
      port_name: "pom-sdnsw1 Port 21"
    destination:
      switch: "10.127.0.104"
      port: "unknown"
      port_name: "moc-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-009"
    friendly_name: "pom-sdnsw1:22 → doc-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.138"
      port: 22
      port_name: "pom-sdnsw1 Port 22"
    destination:
      switch: "10.127.0.200"
      port: "unknown"
      port_name: "doc-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-010"
    friendly_name: "msf-sdnsw1:5 → MSF-SW01                                         |:Unknown"
    source:
      switch: "10.127.0.221"
      port: 5
      port_name: "msf-sdnsw1 Port 5"
    destination:
      switch: "10.120.121.21"
      port: "unknown"
      port_name: "MSF-SW01                                         | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-011"
    friendly_name: "msf-sdnsw1:6 → MSF-SW02                                         |:Unknown"
    source:
      switch: "10.127.0.221"
      port: 6
      port_name: "msf-sdnsw1 Port 6"
    destination:
      switch: "10.120.121.22"
      port: "unknown"
      port_name: "MSF-SW02                                         | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-012"
    friendly_name: "msf-sdnsw1:21 → doc-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.221"
      port: 21
      port_name: "msf-sdnsw1 Port 21"
    destination:
      switch: "10.127.0.200"
      port: "unknown"
      port_name: "doc-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-013"
    friendly_name: "msf-sdnsw1:22 → moc-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.221"
      port: 22
      port_name: "msf-sdnsw1 Port 22"
    destination:
      switch: "10.127.0.104"
      port: "unknown"
      port_name: "moc-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-014"
    friendly_name: "msf-sdnsw1:24 → msf-3942-lab                                     |:Unknown"
    source:
      switch: "10.127.0.221"
      port: 24
      port_name: "msf-sdnsw1 Port 24"
    destination:
      switch: "10.127.0.251"
      port: "unknown"
      port_name: "msf-3942-lab                                     | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-015"
    friendly_name: "moc-sdnsw1:1 → cov-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.104"
      port: 1
      port_name: "moc-sdnsw1 Port 1"
    destination:
      switch: "10.127.0.137"
      port: "unknown"
      port_name: "cov-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-016"
    friendly_name: "moc-sdnsw1:2 → pom-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.104"
      port: 2
      port_name: "moc-sdnsw1 Port 2"
    destination:
      switch: "10.127.0.138"
      port: "unknown"
      port_name: "pom-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-017"
    friendly_name: "moc-sdnsw1:3 → msf-sdnsw1                                       |:Unknown"
    source:
      switch: "10.127.0.104"
      port: 3
      port_name: "moc-sdnsw1 Port 3"
    destination:
      switch: "10.127.0.221"
      port: "unknown"
      port_name: "msf-sdnsw1                                       | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-018"
    friendly_name: "moc-sdnsw1:4 → MOC-SW01                                         |:Unknown"
    source:
      switch: "10.127.0.104"
      port: 4
      port_name: "moc-sdnsw1 Port 4"
    destination:
      switch: "10.120.4.21"
      port: "unknown"
      port_name: "MOC-SW01                                         | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"

  - name: "link-019"
    friendly_name: "moc-sdnsw1:5 → vss-aggsw02                                      |:Unknown"
    source:
      switch: "10.127.0.104"
      port: 5
      port_name: "moc-sdnsw1 Port 5"
    destination:
      switch: "10.120.0.30"
      port: "unknown"
      port_name: "vss-aggsw02                                      | unknown"
    expected_power_range:
      tx_min: -20.0
      tx_max: 10.0
      rx_min: -30.0
      rx_max: -5.0
    fiber_type: "single-mode"
    distance_km: 10
    active: true
    discovery_method: "lldp"


monitoring:
  poll_interval_seconds: 300
  retention_days: 90
  anomaly_threshold_db: 3.0
  temperature_threshold_c: 70

snmp:
  community: "public"
  timeout_seconds: 5
  retries: 3
